#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# populate env vars
if [ -f ~/.config/shell/environment ]; then
    . ~/.config/shell/environment
fi

# configure shell aliases
if [ -f ~/.config/shell/aliases ]; then
    . ~/.config/shell/aliases
fi

# hacky fix to get ALT + . behaviour from Bash back
# https://stackoverflow.com/questions/8344699/how-to-repeat-the-last-part-of-a-previous-command
bindkey '\e.' insert-last-word
