#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# populate env vars
if [ -f ~/.config/shell/environment ]; then
    . ~/.config/shell/environment
fi

# configure shell aliases
if [ -f ~/.config/shell/aliases ]; then
    . ~/.config/shell/aliases
fi

# hacky fix to get ALT + . behaviour from Bash back
# https://stackoverflow.com/questions/8344699/how-to-repeat-the-last-part-of-a-previous-command
bindkey '\e.' insert-last-word


# add directories to PATH

# ~/.local/bin looks a bit more stupid than ~/bin but is the preferred location by the XDG directory spec
# https://specifications.freedesktop.org/basedir-spec/latest/
export PATH=$PATH:~/.local/bin

# zsh will add a line break and a percent sign to any output that lacks a newline
# this is intended to prevent weirdness when the prompt ends up on the same line as the output
# but i think always having nicely looking prompts is not worth having unexpected characters in my shell output
# this will still print the line break, but no extra character
export PROMPT_CR
export PROMPT_SP
export PROMPT_EOL_MARK=''
